// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Program = 2,
  Barline = 3,
  DottedRhythm = 6,
  Note = 7,
  Rest = 8,
  Chord = 9,
  Metadata = 12,
  Composer = 13,
  KeySignature = 14,
  NoteLength = 15,
  Tempo = 16,
  TimeSignature = 17,
  Title = 18,
  TuneNumber = 19
